- name: delete ec2 instances
  hosts: local
  connection: local
  tasks:
    - name: delete mongodb
      amazon.aws.ec2_instance:
        instance_ids:
          - i-0a47f501faa1afa95
        state: absent
        wait: true

    - name: delete redis
      amazon.aws.ec2_instance:
        instance_ids:
          - i-09a652ae4a2297427
        state: absent
        wait: true

    - name: delete mysql
      amazon.aws.ec2_instance:
        instance_ids:
          - i-00d0843c0db970be9
        state: absent
        wait: true

    - name: delete rabbitmq
      amazon.aws.ec2_instance:
        instance_ids:
          - i-0b6fb5d434bb56e15
        state: absent
        wait: true

    - name: delete catalogue
      amazon.aws.ec2_instance:
        instance_ids:
          - i-09ea68c3e2c6a7480
        state: absent
        wait: true